# Generated by Django 5.2.17 on 2026-10-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Serviço')),
                ('setor_executor', models.CharField(default='Oficina (Mecânica)', max_length=100, verbose_name='Setor Executor')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado (Aguardando Análise)'), ('AGUARDANDO_AUTORIZACAO', 'Aguardando Autorização Administrativa'), ('AUTORIZADO', 'Autorizado / Em Fila'), ('EM_EXECUCAO', 'Em Execução na Oficina'), ('CONCLUIDO', 'Concluído')], default='SOLICITADO', max_length=30, verbose_name='Status do Serviço')),
                ('precisa_autorizacao', models.BooleanField(default=True, verbose_name='Requer Autorização?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=20, verbose_name='Decisão')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Justificativa / Observação')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacao', to='ordens.servico', verbose_name='Serviço Relacionado')),
            ],
            options={
                'verbose_name': 'Autorização',
                'verbose_name_plural': 'Autorizações',
            },
        ),
    ]
