# Generated by Django 5.2.17 on 2026-10-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Serviço')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('AUTORIZADO', 'Autorizado'), ('RECUSADO', 'Recusado'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído')], default='SOLICITADO', max_length=30, verbose_name='Status')),
                ('precisa_autorizacao', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='ExecucaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.CharField(max_length=150, verbose_name='Nome do Executor / Mecânico / Pintor')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, verbose_name='Início da Execução')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Execução')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='ordens.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Execução de Serviço',
                'verbose_name_plural': 'Execuções de Serviços',
            },
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacao', to='ordens.servico')),
            ],
        ),
    ]
