# Generated by Django 5.2.17 on 2026-10-07 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('contato', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato')),
                ('tipo_servico', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='DemandaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Demanda')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Demanda')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=15, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATRIBUIDA', 'Atribuída'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída'), ('NAO_CONCLUIDA', 'Não Concluída / Impedimento')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('veiculo_relacionado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Veículo Relacionado (Opcional)')),
                ('os_relacionada', models.CharField(blank=True, max_length=50, null=True, verbose_name='OS Relacionada (Opcional)')),
                ('motivo_ocorrencia', models.TextField(blank=True, help_text='Motivo em caso de não conclusão ou imprevisto', null=True, verbose_name='Motivo da Ocorrência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (Auxiliar)')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Demanda Externa',
                'verbose_name_plural': 'Demandas Externas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='evidencias/%Y/%m/%d/', verbose_name='Fotografia')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor da Foto')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Evidência Fotográfica',
                'verbose_name_plural': 'Evidências Fotográficas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
