# Generated by Django 5.2.17 on 2026-10-07 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0002_fornecedor_demandaexterna_evidenciafoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Ocorrência')),
                ('setor_solicitante', models.CharField(max_length=100, verbose_name='Setor Solicitante')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDA', 'Resolvida')], default='PENDENTE', max_length=20)),
                ('veiculo_relacionado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa/Chassi')),
                ('os_relacionada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da OS')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='demandaexterna',
            name='motivo_ocorrencia',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='demandaexterna',
            name='os_relacionada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OS Relacionada'),
        ),
        migrations.AlterField(
            model_name='demandaexterna',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='demandaexterna',
            name='veiculo_relacionado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Veículo Relacionado'),
        ),
    ]
