# Generated by Django 5.2.17 on 2026-10-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100, verbose_name='Tipo de Evento (Ex: MUDANCA_ETAPA, OCORRENCIA_CRIADA)')),
                ('descricao', models.TextField(verbose_name='Detalhe da Movimentação')),
                ('autor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsável / Sistema')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='veiculos.cicloveiculo', verbose_name='Ciclo')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Histórico e Auditoria',
                'verbose_name_plural': 'Históricos e Auditorias',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoLavagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FILA', 'Na Fila'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='FILA', max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lavagem', to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='VistoriaQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('POS_OFICINA', 'Qualidade Pós-Oficina'), ('FINAL', 'Qualidade Final')], max_length=20)),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado / Gerou Nova Ocorrência')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='veiculos.veiculo')),
            ],
        ),
    ]
