# Generated by Django 5.2.17 on 2026-10-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoLavagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FILA', 'Na Fila de Lavagem'), ('EM_ANDAMENTO', 'Em Execução'), ('CONCLUIDO', 'Concluído')], default='FILA', max_length=20, verbose_name='Status da Lavagem')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável pela Lavagem')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lavagem', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Processo de Lavagem',
                'verbose_name_plural': 'Processos de Lavagem',
            },
        ),
        migrations.CreateModel(
            name='VistoriaQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('POS_OFICINA', 'Qualidade Pós-Oficina'), ('FINAL', 'Qualidade Final (Pós-Lavagem)')], max_length=20, verbose_name='Etapa da Qualidade')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado (Liberado para próxima etapa)'), ('REPROVADO', 'Reprovado / Gerou Nova Ocorrência')], default='APROVADO', max_length=20, verbose_name='Resultado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Laudo / Observações')),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Vistoria de Qualidade',
                'verbose_name_plural': 'Vistorias de Qualidade',
                'ordering': ['-realizado_em'],
            },
        ),
    ]
