# Generated by Django 5.2.17 on 2026-10-10 18:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processolavagem',
            options={'ordering': ['criado_em'], 'verbose_name': 'Processo de Lavagem', 'verbose_name_plural': 'Processos de Lavagem'},
        ),
        migrations.RemoveField(
            model_name='processolavagem',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='processolavagem',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavagens', to='veiculos.cicloveiculo', verbose_name='Ciclo Operacional'),
        ),
        migrations.AddField(
            model_name='processolavagem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 10, 10, 18, 44, 50, 988936, tzinfo=datetime.timezone.utc), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processolavagem',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='vistoriaqualidade',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vistorias', to='veiculos.cicloveiculo'),
        ),
        migrations.AlterField(
            model_name='processolavagem',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conclusão da Lavagem'),
        ),
        migrations.AlterField(
            model_name='processolavagem',
            name='iniciado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Lavagem'),
        ),
        migrations.AlterField(
            model_name='processolavagem',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='processolavagem',
            name='status',
            field=models.CharField(choices=[('FILA', 'Na Fila'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='FILA', max_length=20, verbose_name='Status'),
        ),
    ]
