# Generated by Django 5.2.17 on 2026-10-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('chassi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chassi')),
                ('marca_modelo', models.CharField(max_length=150, verbose_name='Marca/Modelo')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor')),
                ('loja', models.CharField(choices=[('GRAN_VIA', 'Gran Via'), ('EUROVIA', 'Eurovia'), ('PIEDADE', 'Piedade')], max_length=20, verbose_name='Loja de Destino')),
                ('status', models.CharField(choices=[('AVALIADOR', 'Avaliador'), ('OFICINA', 'Oficina'), ('QUALIDADE_POS', 'Qualidade Pós-Oficina'), ('LAVAGEM', 'Lavagem'), ('QUALIDADE_FINAL', 'Qualidade Final'), ('SHOWROOM', 'Showroom / Loja')], default='AVALIADOR', max_length=20, verbose_name='Etapa Atual')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CicloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ciclo', models.PositiveIntegerField(verbose_name='Número do Ciclo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ciclo Ativo?')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ciclo do Veículo',
                'verbose_name_plural': 'Ciclos dos Veículos',
                'ordering': ['-numero_ciclo'],
            },
        ),
    ]
