# Generated by Django 5.2.17 on 2026-10-07 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('concessionaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concessionaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='concessionaria.concessionaria')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='accounts.funcao')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='concessionaria.unidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VinculoSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_setor', to='accounts.funcionario')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_funcionarios', to='concessionaria.setor')),
            ],
            options={
                'verbose_name': 'Vínculo com Setor',
                'verbose_name_plural': 'Vínculos com Setores',
                'constraints': [models.UniqueConstraint(fields=('funcionario', 'setor'), name='unique_funcionario_setor')],
            },
        ),
    ]
