# Generated by Django 5.2.17 on 2026-10-09 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('concessionaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='concessionaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='concessionaria.concessionaria'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='accounts.funcao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='concessionaria.unidade'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vinculosetor',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_setor', to='accounts.funcionario'),
        ),
        migrations.AddField(
            model_name='vinculosetor',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_funcionarios', to='concessionaria.setor'),
        ),
        migrations.AddConstraint(
            model_name='vinculosetor',
            constraint=models.UniqueConstraint(fields=('funcionario', 'setor'), name='unique_funcionario_setor'),
        ),
    ]
